// File: @/app/layout.tsx
import type { Metadata } from 'next';
import { StackProvider, StackTheme } from '@stackframe/stack';
import { stackServerApp } from '../stack';
import { Poppins } from 'next/font/google';
import './globals.css';
import { ConvexClientProvider } from './ConvexClientProvider';
import { Toaster } from 'sonner';

const poppins = Poppins({
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	variable: '--font-poppins',
	subsets: ['latin'],
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${poppins.variable}  antialiased`}>
				<StackProvider app={stackServerApp}>
					<StackTheme>
						<ConvexClientProvider>
							{children}
							<Toaster />
						</ConvexClientProvider>
					</StackTheme>
				</StackProvider>
			</body>
		</html>
	);
}
